#set --export AWS_ACCESS_KEY_ID AKIAICI6Y5ESKNCJUUKQ
#set --export AWS_SECRET_ACCESS_KEY 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


# New TID
set --export AWS_ACCESS_KEY_ID AKIAI5BTSFID5QSRDGEQ
set --export AWS_SECRET_ACCESS_KEY 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
